spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    username: sa
#    url: jdbc:h2:mem:db;
#    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: 'true'
      path: /h2
  application:
    name: user-microservice
  config:
    import: optional:file:.env[.properties]
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      hbm2ddl:
        auto: update
      show-sql: 'true'
      ddl-auto: update
    show-sql: 'true'
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka
server:
  port: '8081'
